### ISSUE TITLE
License

### ISSUE THREAD

**Issue by abarax** [jcalazan/glucose-tracker#12]
Have you released this code under a certain license?

**Comment by ex-nerd** [comment]
@jcalazan IANAL but I've spent a lot of time examining licensing for open source projects..  Technically (despite what you say in this issue thread), any code/art/whatever in the US (where Github is hosting your stuff) without a license defaults to "all rights reserved".  This means that though the code is visible to be read, it is not "open source" in the sense of an OSI-approved license.  Nor can anyone else take your code and modify it (or honestly, even just use it) because you still retain all of those rights.  It's the license that grants people the right to fork/copy/modify your code.

Github has set up http://choosealicense.com/ to help project maintainers decide between various licensing options.   If you just want your code to be open and don't mind how other people use it, look at MIT or Modified BSD.  If you want something copyleft that will make sure that forks of your code continue to be shared with the community, go for the GPL.

**Comment by jcalazan** [comment]
Sorry guys, completely forgotten about this ticket.  Just added the MIT license.
